module.exports = [ {
    id: 0,
    option: "真心话大冒险之真心话",
    awards: [ {
        name: "描述经历过最尴尬的事",
        color: "#83ecc6"
    }, {
        name: "今天穿什么颜色的内裤",
        color: "#ec807a"
    }, {
        name: "第一次啪啪啪几岁",
        color: "#9beaea"
    }, {
        name: "做过最疯狂的事是什么",
        color: "#f8e4ad"
    }, {
        name: "单身的感觉好吗",
        color: "#5dcbc7"
    }, {
        name: "你被绿过吗",
        color: "#e4d571"
    }, {
        name: "打过几次分手炮",
        color: "#7ecad8"
    }, {
        name: "上一次啪啪啪是什么时候",
        color: "#d2718c"
    }, {
        name: "你出轨过么",
        color: "#73cac3"
    }, {
        name: "多久没看书了",
        color: "#6cb1d5"
    } ]
}, {
    id: 1,
    option: "真心话大冒险之大冒险",
    awards: [ {
        name: "大声喊 我是猪 我真的是猪",
        color: "#83ecc6"
    }, {
        name: "搭讪一个陌生人",
        color: "#ec807a"
    }, {
        name: "做个性感的表情或动作",
        color: "#9beaea"
    }, {
        name: "任选个异性夸赞一分钟",
        color: "#f8e4ad"
    }, {
        name: "对着杯子表白一分钟",
        color: "#5dcbc7"
    }, {
        name: "打电话给异性说晚安",
        color: "#e4d571"
    }, {
        name: "大声唱首儿歌",
        color: "#7ecad8"
    } ]
}, {
    id: 2,
    option: "下个节日让我男票给我买什么礼物？",
    awards: [ {
        name: "SixGod香水",
        color: "#83ecc6"
    }, {
        name: "狗粮",
        color: "#ec807a"
    }, {
        name: "YSL52号口红",
        color: "#9beaea"
    }, {
        name: "AJ1篮球鞋",
        color: "#f8e4ad"
    }, {
        name: "香奈儿包包",
        color: "#5dcbc7"
    }, {
        name: "验孕棒",
        color: "#e4d571"
    }, {
        name: "有没有男票心里没点数",
        color: "#7ecad8"
    }, {
        name: "SK-ll神仙水",
        color: "#d2718c"
    } ]
}, {
    id: 3,
    option: "今天中午吃什么？",
    awards: [ {
        name: "黄焖鸡米饭",
        color: "#83ecc6"
    }, {
        name: "牛肉拉面",
        color: "#ec807a"
    }, {
        name: "自己多少斤心里没点数",
        color: "#9beaea"
    }, {
        name: "水饺",
        color: "#f8e4ad"
    }, {
        name: "蛋炒饭",
        color: "#5dcbc7"
    }, {
        name: "兰州拉面",
        color: "#e4d571"
    }, {
        name: "沙县小吃",
        color: "#7ecad8"
    }, {
        name: "烤肉饭",
        color: "#d2718c"
    }, {
        name: "米线",
        color: "#73cac3"
    } ]
}, {
    id: 4,
    option: "抽取狼人杀身份牌",
    awards: [ {
        index: 0,
        name: "预言家",
        color: "#83ecc6"
    }, {
        index: 1,
        name: "狼人",
        color: "#ec807a"
    }, {
        index: 2,
        name: "村民",
        color: "#FFC928"
    }, {
        index: 3,
        name: "狼人",
        color: "#9beaea"
    }, {
        index: 4,
        name: "村民",
        color: "#f8e4ad"
    }, {
        index: 5,
        name: "狼人",
        color: "#5dcbc7"
    }, {
        index: 6,
        name: "村民",
        color: "#e4d571"
    }, {
        index: 7,
        name: "狼人",
        color: "#7ecad8"
    }, {
        index: 8,
        name: "村民",
        color: "#d2718c"
    }, {
        index: 9,
        name: "猎人",
        color: "#73cac3"
    }, {
        index: 10,
        name: "女巫",
        color: "#6cb1d5"
    }, {
        index: 11,
        name: "丘比特",
        color: "#864284"
    }, {
        index: 12,
        name: "白痴",
        color: "#efb5a4"
    } ]
}, {
    id: 5,
    option: "是什么激励我努力上班？",
    awards: [ {
        name: "穷",
        color: "#83ecc6"
    }, {
        name: "为了房子",
        color: "#ec807a"
    }, {
        name: "穷",
        color: "#9beaea"
    }, {
        name: "为了男人",
        color: "#f8e4ad"
    }, {
        name: "穷",
        color: "#5dcbc7"
    }, {
        name: "为了女人",
        color: "#e4d571"
    }, {
        name: "穷",
        color: "#7ecad8"
    }, {
        name: "为了孩子",
        color: "#d2718c"
    } ]
}, {
    id: 6,
    option: "明天约会去干点啥？",
    awards: [ {
        name: "看个电影",
        color: "#83ecc6"
    }, {
        name: "去游乐场玩",
        color: "#ec807a"
    }, {
        name: "一起打台球",
        color: "#9beaea"
    }, {
        name: "小吃街吃一圈",
        color: "#f8e4ad"
    }, {
        name: "一起去爬山",
        color: "#5dcbc7"
    }, {
        name: "看个展览",
        color: "#e4d571"
    }, {
        name: "学习做陶艺",
        color: "#7ecad8"
    }, {
        name: "玩密室逃脱",
        color: "#d2718c"
    } ]
}, {
    id: 7,
    option: "周末做什么好？",
    awards: [ {
        name: "逛街",
        color: "#83ecc6"
    }, {
        name: "睡觉",
        color: "#ec807a"
    }, {
        name: "吃大餐",
        color: "#9beaea"
    }, {
        name: "约会",
        color: "#f8e4ad"
    }, {
        name: "看电影",
        color: "#5dcbc7"
    }, {
        name: "游乐场",
        color: "#e4d571"
    }, {
        name: "爬山",
        color: "#7ecad8"
    }, {
        name: "健身房",
        color: "#d2718c"
    } ]
}, {
    id: 8,
    option: "十一国庆去哪玩",
    awards: [ {
        name: "凤凰古城",
        color: "#83ecc6"
    }, {
        name: "张家界",
        color: "#ec807a"
    }, {
        name: "乌镇",
        color: "#9beaea"
    }, {
        name: "鼓浪屿",
        color: "#f8e4ad"
    }, {
        name: "千岛湖",
        color: "#5dcbc7"
    }, {
        name: "稻城",
        color: "#e4d571"
    }, {
        name: "大理",
        color: "#7ecad8"
    }, {
        name: "丽江",
        color: "#d2718c"
    } ]
}, {
    id: 9,
    option: "谁去食堂带饭？",
    awards: [ {
        name: "老大",
        color: "#83ecc6"
    }, {
        name: "老二",
        color: "#ec807a"
    }, {
        name: "老三",
        color: "#9beaea"
    }, {
        name: "老四",
        color: "#f8e4ad"
    }, {
        name: "老五",
        color: "#5dcbc7"
    }, {
        name: "老六",
        color: "#e4d571"
    } ]
} ];